In [1]:
import numpy as np

docs = ['go india',
        'india india',
        'hip hip hurray',
        'jeetega bhai jeetega india jeetega',
        'bharat mata ki jai',
        'kohli kohli',
        'sachin sachin',
        'dhoni dhoni',
        'modi ji ki jai',
        'inquilab zindabad']

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

2025-06-19 16:45:26.580008: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1750351526.598344    2213 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1750351526.603660    2213 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1750351526.619465    2213 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1750351526.619521    2213 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1750351526.619523    2213 computation_placer.cc:177] computation placer alr

In [3]:
tokenizer.fit_on_texts(docs)

In [4]:
len(tokenizer.word_index)

17

In [5]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [6]:
from tensorflow.keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [11]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(input_dim=17, output_dim=2, input_length=5))
model.build(input_shape=(None, 5))
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 5, 2)           │            34 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 34 (136.00 B)

 Trainable params: 34 (136.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.compile('adam','accuracy')

In [13]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step
[[[-4.2084605e-04  1.0285154e-03]
  [-3.6615431e-02 -4.4056725e-02]
  [ 6.9208518e-03 -3.9273370e-02]
  [ 6.9208518e-03 -3.9273370e-02]
  [ 6.9208518e-03 -3.9273370e-02]]

 [[-3.6615431e-02 -4.4056725e-02]
  [-3.6615431e-02 -4.4056725e-02]
  [ 6.9208518e-03 -3.9273370e-02]
  [ 6.9208518e-03 -3.9273370e-02]
  [ 6.9208518e-03 -3.9273370e-02]]

 [[ 4.0543053e-02  3.1035058e-03]
  [ 4.0543053e-02  3.1035058e-03]
  [ 1.6447816e-02  4.1769337e-02]
  [ 6.9208518e-03 -3.9273370e-02]
  [ 6.9208518e-03 -3.9273370e-02]]

 [[-3.6358833e-05  3.6581978e-03]
  [-4.4134915e-02 -1.4355004e-02]
  [-3.6358833e-05  3.6581978e-03]
  [-3.6615431e-02 -4.4056725e-02]
  [-3.6358833e-05  3.6581978e-03]]

 [[ 4.7489848e-02  3.1232011e-02]
  [-1.2479067e-02 -4.5416724e-02]
  [-1.9290185e-02 -3.7791193e-02]
  [ 4.1768197e-02 -1.2330733e-02]
  [ 6.9208518e-03 -3.9273370e-02]]

 [[ 2.0499114e-02  3.5419676e-02]
  [ 2.0499114e-02  3.5419676e-02]
  [ 6.9208518e-03 -3.9273370e-02]

I0000 00:00:1750351799.569677    2353 service.cc:152] XLA service 0x712ae00043e0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1750351799.569738    2353 service.cc:160]   StreamExecutor device (0): NVIDIA GeForce RTX 2050, Compute Capability 8.6
I0000 00:00:1750351799.580003    2353 cuda_dnn.cc:529] Loaded cuDNN version 90300
I0000 00:00:1750351799.684094    2353 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
