In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow
# import keras
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

2025-04-13 17:42:20.366993: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1744566140.383658    6265 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1744566140.389131    6265 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1744566140.404592    6265 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1744566140.404606    6265 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1744566140.404607    6265 computation_placer.cc:177] computation placer alr

In [5]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/home/zahir/Tf_gpu/tfgpu1/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
I0000 00:00:1744566145.655524    6265 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1767 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2050, pci bus id: 0000:01:00.0, compute capability: 8.6


In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.get_weights()

[array([[ 0.86763704, -1.1297698 ],
        [ 0.46616912, -0.87727165]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.0204096],
        [-0.6039188]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32),
               np.array([0.],dtype=np.float32)]

In [10]:
model.set_weights(new_weights)

In [11]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [13]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75


I0000 00:00:1744566546.572579    6334 service.cc:152] XLA service 0x7f11e8005b10 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1744566546.572702    6334 service.cc:160]   StreamExecutor device (0): NVIDIA GeForce RTX 2050, Compute Capability 8.6
2025-04-13 17:49:06.616949: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1744566546.711905    6334 cuda_dnn.cc:529] Loaded cuDNN version 90300


4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 28.1787  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 28.3823 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 23.7739 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.0351 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 20.7325 
Epoch 6/75


I0000 00:00:1744566547.036719    6334 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 30.0076 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.4809
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 21.3423 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.4035 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22.3722 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.9889 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 28.6948 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 26.4574 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 26.4691 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22.1083 
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 21.6176 
Epoch 17/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 19.6235
Epoch 18/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.0619 
Epoch 19/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 23.3347 
Epoch 20/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 17.6638
Epoch 21/75
4/4 ━━━━━━━━━━━

In [14]:
model.get_weights()

[array([[0.3734245 , 0.3734245 ],
        [0.36552507, 0.36552507]], dtype=float32),
 array([0.27217847, 0.27217847], dtype=float32),
 array([[0.37279776],
        [0.37279776]], dtype=float32),
 array([0.20474899], dtype=float32)]